version: "3.8"
services:
    todo-app:
        container_name: "todo-app"
        image: jaydenlsf/todo-app:${VERSION}
        build: .
        environment:
            DATABASE_URI: sqlite:///data.db
            SECRET_KEY: ${SECRET_KEY}
        ports:
        - target: 5000
          published: 80