apiVersion: v1
kind: Secret
metadata:
  name: todo-app
type: Opaque
stringData:
  secretKey: { { SECRET_KEY } }
  databaseURI: { { DATABASE_URI } }
---
# MySQL
apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opague
stringData:
  rootPassword: { { MYSQL_ROOT_PASSWORD } }
  database: { { MYSQL_DATABASE } }
